{% set name = "sphinx-design" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/executablebooks/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: c3cbcbef4a176295f146adfca5d998ff161dd2d3750ff6abac58e8df2e5e1243

build:
  number: 2
  script:
    - {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - sphinx >=6,<9
    - flit-core
  run:
    - python >={{ python_min }}
    - sphinx >=6,<9

test:
  requires:
    - myst-parser
    - pytest
    - pytest-regressions
    - defusedxml
    - python {{ python_min }}
  source_files:
    - tests/
  imports:
    - sphinx_design
  commands:
    - pytest tests -vv

about:
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A sphinx extension for designing beautiful, screen-size responsive web components.
  home: https://github.com/executablebooks/sphinx-design
  doc_url: https://sphinx-design.readthedocs.io

extra:
  recipe-maintainers:
    - awvwgk
    - dopplershift
